"""
    Staphylococcus aureus subsp. aureus NCTC 8325 chromosome, complete genome
    Species: Stapyhlacoccus aureus
    NCBI Referance Sequence: NC_007795.1
    Region: >NC_007795.1: 1317076-1318338
"""

seq= "ATGAAGTTTACAAATTTAACAGCTAAAGAGTTTGGTGCCTTTACAGATAGCATGCCATACAGTCATTTCACGCAAACTGTTGGCCACTATGAGTTAAAGCTTGCTGAAGGTTATGAAACACATTTAGTGGGAATAAAAAACAATAATAACGAGGTCATTGCAGCTTGCTTACTTACTGCTGTACCTGTTATGAAAGTGTTCAAGTATTTTTATTCAAATCGCGGTCCAGTGATTGATTATGAAAATCAAGAACTCGTACACTTTTTCTTTAATGAATTATCAAAATATGTTAAAAAACATCGTTGTCTATACCTACATATCGATCCATATTTACCATATCAATACTTGAATCATGATGGCGAGATTACAGGTAATGCTGGTAATGATTGGTTCTTTGATAAAATGAGTAACTTAGGATTTGAACATACTGGATTCCATAAAGGATTTGATCCTGTGCTACAAATTCGTTATCACTCAGTGTTAGATTTAAAAGATAAAACAGCAGATGACATCATTAAAAATATGGATGGACTTAGAAAAAGAAACACGAAAAAAGTTAAAAAGAATGGTGTTAAAGTAAGATTTTTATCTGAAGAAGAACTACCAATTTTTAGATCATTTATGGAAGATACGTCAGAATCAAAAGCTTTTGCTGATCGTGATGACAAATTTTACTACAATCGCTTAAAATATTACAAAGACCGTGTGTTAGTACCTTTAGCGTATATCAACTTTGATGAATATATTAAAGAACTAAACGAAGAGCGTGATATTTTAAATAAAGATTTAAATAAAGCGTTAAAGGATATTGAAAAACGTCCTGAAAATAAAAAAGCACATAACAAGCGAGATAACTTACAACAACAACTTGATGCAAATGAGCAAAAGATTGAAGAAGGTAAACGTCTACAAGAAGAACATGGTAATGAATTACCTATCTCTGCTGGTTTCTTCTTTATCAATCCATTTGAAGTTGTTTATTATGCTGGTGGTACATCAAATGCATTCCGTCATTTTGCCGGAAGTTATGCAGTGCAATGGGAAATGATTAATTATGCATTAAATCATGGCATTGACCGTTATAATTTCTATGGTGTTAGTGGTAAATTTACAGAAGATGCTGAAGATGCTGGTGTAGTTAAATTCAAAAAAGGTTACAATGCTGAAATTATTGAATATGTTGGTGACTTTATTAAACCAATTAATAAACCTGTTTACGCAGCATATACCGCACTTAAAAAAGTTAAAGACAGAATTTTTTAG"


def base_count(s):

    counter = {
        "A" : 0, 
        "C" : 0, 
        "G" : 0, 
        "T" : 0
    }

    for base in s:
        counter[base] += 1

    return counter
        
base_count(seq)


a = 0
t = 0
g = 0
c = 0

for base in seq:
    if base == "A":
        a += 1
    elif base == "T":
        t += 1
    elif base == "G":
        g += 1
    elif base == "C":
        c += 1
    
per_a = a / len(seq) * 100
per_t = t / len(seq) * 100
per_g = g / len(seq) * 100
per_c = c / len(seq) * 100

gc = (g + c) / len(seq) * 100
print("=================================================\n")
print("Staphylococcus aureus NCTC 8325 Sequence Analysis")
print("=================================================\n")
print(f"          Lenght of seq: {len(seq)}")
print("\n========================================\n")
print(base_count(seq))
print("\n=========================================\n")
print(f"Adenine  (A): {per_a:.2f}%")
print(f"Tymine   (T): {per_t:.2f}%")
print(f"Guanine  (G): {per_g:.2f}%")
print(f"Citosine (C): {per_c:.2f}%")
print(f"\nGC Content  : {gc:.2f}%")
print("\n==========================================\n")




