"""
    Staphylococcus aureus subsp. aureus NCTC 8325 chromosome, complete genome
    Species: Stapyhlacoccus aureus
    NCBI Referance Sequence: NC_007795.1
    Region: >NC_007795.1: 1317076-1318338

"""

seq= "ATGAAGTTTACAAATTTAACAGCTAAAGAGTTTGGTGCCTTTACAGATAGCATGCCATACAGTCATTTCACGCAAACTGTTGGCCACTATGAGTTAAAGCTTGCTGAAGGTTATGAAACACATTTAGTGGGAATAAAAAACAATAATAACGAGGTCATTGCAGCTTGCTTACTTACTGCTGTACCTGTTATGAAAGTGTTCAAGTATTTTTATTCAAATCGCGGTCCAGTGATTGATTATGAAAATCAAGAACTCGTACACTTTTTCTTTAATGAATTATCAAAATATGTTAAAAAACATCGTTGTCTATACCTACATATCGATCCATATTTACCATATCAATACTTGAATCATGATGGCGAGATTACAGGTAATGCTGGTAATGATTGGTTCTTTGATAAAATGAGTAACTTAGGATTTGAACATACTGGATTCCATAAAGGATTTGATCCTGTGCTACAAATTCGTTATCACTCAGTGTTAGATTTAAAAGATAAAACAGCAGATGACATCATTAAAAATATGGATGGACTTAGAAAAAGAAACACGAAAAAAGTTAAAAAGAATGGTGTTAAAGTAAGATTTTTATCTGAAGAAGAACTACCAATTTTTAGATCATTTATGGAAGATACGTCAGAATCAAAAGCTTTTGCTGATCGTGATGACAAATTTTACTACAATCGCTTAAAATATTACAAAGACCGTGTGTTAGTACCTTTAGCGTATATCAACTTTGATGAATATATTAAAGAACTAAACGAAGAGCGTGATATTTTAAATAAAGATTTAAATAAAGCGTTAAAGGATATTGAAAAACGTCCTGAAAATAAAAAAGCACATAACAAGCGAGATAACTTACAACAACAACTTGATGCAAATGAGCAAAAGATTGAAGAAGGTAAACGTCTACAAGAAGAACATGGTAATGAATTACCTATCTCTGCTGGTTTCTTCTTTATCAATCCATTTGAAGTTGTTTATTATGCTGGTGGTACATCAAATGCATTCCGTCATTTTGCCGGAAGTTATGCAGTGCAATGGGAAATGATTAATTATGCATTAAATCATGGCATTGACCGTTATAATTTCTATGGTGTTAGTGGTAAATTTACAGAAGATGCTGAAGATGCTGGTGTAGTTAAATTCAAAAAAGGTTACAATGCTGAAATTATTGAATATGTTGGTGACTTTATTAAACCAATTAATAAACCTGTTTACGCAGCATATACCGCACTTAAAAAAGTTAAAGACAGAATTTTTTAG"

lenght=len(seq)


def base_count(s):

    counter = {
        "A" : 0, 
        "C" : 0, 
        "G" : 0, 
        "T" : 0
    }

    for base in s:
        counter[base] += 1

    return counter
        
base_count(seq)

print("==========================================\n")
print(f"          Lenght of seq: {lenght}")
print("\n========================================\n")
print(base_count(seq))
print("\n=========================================\n")


